version: "3"
services:
  server:
    build: .
    depends_on:
      - mongo
    ports:
      - "3030:3030"
    restart: unless-stopped
    command: bash -c "./wait-for.sh --timeout=0 mongo:27017 && node index.js"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
